# Use root/example as user/password credentials
version: '3.1'

services:

  mongo:
    build:
      context: ./bootstrap
      dockerfile: Dockerfile
    image: mongo
    command: --replSet myRs 
    environment:
      MONGO_INITDB_DATABASE: admin
    ports:
      - "27017:27017"
